export const REDIRECTS = new Map<string, `https://${string}`>([
	["creator-troupe", "https://thatskyapplication.com/creator-troupe"],
	["cretro", "https://thatskyapplication.com/creator-troupe"],
	["ct", "https://thatskyapplication.com/creator-troupe"],
	["skycord", "https://discord.gg/thatskygame"],
	["skydc", "https://discord.gg/thatskygame"],
	["skydiscord", "https://discord.gg/thatskygame"],
	["skyfacebook", "https://facebook.com/thatskygame"],
	["skyfb", "https://facebook.com/thatskygame"],
	["skyig", "https://instagram.com/thatskygame"],
	["skyinsta", "https://instagram.com/thatskygame"],
	["skyinstagram", "https://instagram.com/thatskygame"],
	["skymerch", "https://thatskyshop.com"],
	["skymerchandise", "https://thatskyshop.com"],
	["skyreddit", "https://reddit.com/r/SkyGame"],
	["skyreddit2", "https://reddit.com/r/SkyChildrenOfLight"],
	["skytwitter", "https://x.com/thatskygame"],
	["skyx", "https://x.com/thatskygame"],
	["skyyoutube", "https://youtube.com/@thatgamecompany"],
	["skyyt", "https://youtube.com/@thatgamecompany"],
	["skywebstore", "https://webshop.thatskygame.com"],
	["tgc", "https://thatgamecompany.com"],
	["tsa", "https://thatskyapplication.com"],
	["tsg", "https://thatskygame.com"],
	["wiki", "https://sky-children-of-the-light.fandom.com"],
]);
